// Code generated by go-enum
// DO NOT EDIT!

package stockindex

import (
	"fmt"
)

const (
	// IndexTWSE is a Index of type TWSE
	IndexTWSE Index = iota
	// IndexDJI is a Index of type DJI
	IndexDJI
	// IndexNASDAQ is a Index of type NASDAQ
	IndexNASDAQ
	// IndexSP500 is a Index of type SP500
	IndexSP500
)

const _IndexName = "TWSEDJINASDAQSP500"

var _IndexMap = map[Index]string{
	0: _IndexName[0:4],
	1: _IndexName[4:7],
	2: _IndexName[7:13],
	3: _IndexName[13:18],
}

// String implements the Stringer interface.
func (x Index) String() string {
	if str, ok := _IndexMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Index(%d)", x)
}

var _IndexValue = map[string]Index{
	_IndexName[0:4]:   0,
	_IndexName[4:7]:   1,
	_IndexName[7:13]:  2,
	_IndexName[13:18]: 3,
}

// ParseIndex attempts to convert a string to a Index
func ParseIndex(name string) (Index, error) {
	if x, ok := _IndexValue[name]; ok {
		return x, nil
	}
	return Index(0), fmt.Errorf("%s is not a valid Index", name)
}
